package com.aiengineering.domain;

// Represents who authored a chat message — mirrors the roles used by OpenAI's Chat API.
public enum MessageRole {
    USER,       // Message sent by the human end-user
    ASSISTANT,  // Reply generated by the AI model
    SYSTEM      // System-level instruction prompt (persisted for audit; not shown to users)
}
